// Code generated by protoc-gen-go. DO NOT EDIT.
// source: com/digitalasset/ledger/api/v1/ledger_offset.proto

package com_digitalasset_ledger_api_v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LedgerOffset_LedgerBoundary int32

const (
	// Refers to the first transaction.
	LedgerOffset_LEDGER_BEGIN LedgerOffset_LedgerBoundary = 0
	// Refers to the currently last transaction, which is a moving target.
	LedgerOffset_LEDGER_END LedgerOffset_LedgerBoundary = 1
)

var LedgerOffset_LedgerBoundary_name = map[int32]string{
	0: "LEDGER_BEGIN",
	1: "LEDGER_END",
}

var LedgerOffset_LedgerBoundary_value = map[string]int32{
	"LEDGER_BEGIN": 0,
	"LEDGER_END":   1,
}

func (x LedgerOffset_LedgerBoundary) String() string {
	return proto.EnumName(LedgerOffset_LedgerBoundary_name, int32(x))
}

func (LedgerOffset_LedgerBoundary) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_bbe4ac1c1998182f, []int{0, 0}
}

// Describes a specific point on the ledger.
type LedgerOffset struct {
	// Types that are valid to be assigned to Value:
	//	*LedgerOffset_Absolute
	//	*LedgerOffset_Boundary
	Value                isLedgerOffset_Value `protobuf_oneof:"value"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *LedgerOffset) Reset()         { *m = LedgerOffset{} }
func (m *LedgerOffset) String() string { return proto.CompactTextString(m) }
func (*LedgerOffset) ProtoMessage()    {}
func (*LedgerOffset) Descriptor() ([]byte, []int) {
	return fileDescriptor_bbe4ac1c1998182f, []int{0}
}

func (m *LedgerOffset) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LedgerOffset.Unmarshal(m, b)
}
func (m *LedgerOffset) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LedgerOffset.Marshal(b, m, deterministic)
}
func (m *LedgerOffset) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LedgerOffset.Merge(m, src)
}
func (m *LedgerOffset) XXX_Size() int {
	return xxx_messageInfo_LedgerOffset.Size(m)
}
func (m *LedgerOffset) XXX_DiscardUnknown() {
	xxx_messageInfo_LedgerOffset.DiscardUnknown(m)
}

var xxx_messageInfo_LedgerOffset proto.InternalMessageInfo

type isLedgerOffset_Value interface {
	isLedgerOffset_Value()
}

type LedgerOffset_Absolute struct {
	Absolute string `protobuf:"bytes,1,opt,name=absolute,proto3,oneof"`
}

type LedgerOffset_Boundary struct {
	Boundary LedgerOffset_LedgerBoundary `protobuf:"varint,2,opt,name=boundary,proto3,enum=com.digitalasset.ledger.api.v1.LedgerOffset_LedgerBoundary,oneof"`
}

func (*LedgerOffset_Absolute) isLedgerOffset_Value() {}

func (*LedgerOffset_Boundary) isLedgerOffset_Value() {}

func (m *LedgerOffset) GetValue() isLedgerOffset_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *LedgerOffset) GetAbsolute() string {
	if x, ok := m.GetValue().(*LedgerOffset_Absolute); ok {
		return x.Absolute
	}
	return ""
}

func (m *LedgerOffset) GetBoundary() LedgerOffset_LedgerBoundary {
	if x, ok := m.GetValue().(*LedgerOffset_Boundary); ok {
		return x.Boundary
	}
	return LedgerOffset_LEDGER_BEGIN
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*LedgerOffset) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*LedgerOffset_Absolute)(nil),
		(*LedgerOffset_Boundary)(nil),
	}
}

func init() {
	proto.RegisterEnum("com.digitalasset.ledger.api.v1.LedgerOffset_LedgerBoundary", LedgerOffset_LedgerBoundary_name, LedgerOffset_LedgerBoundary_value)
	proto.RegisterType((*LedgerOffset)(nil), "com.digitalasset.ledger.api.v1.LedgerOffset")
}

func init() {
	proto.RegisterFile("com/digitalasset/ledger/api/v1/ledger_offset.proto", fileDescriptor_bbe4ac1c1998182f)
}

var fileDescriptor_bbe4ac1c1998182f = []byte{
	// 226 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x32, 0x4a, 0xce, 0xcf, 0xd5,
	0x4f, 0xc9, 0x4c, 0xcf, 0x2c, 0x49, 0xcc, 0x49, 0x2c, 0x2e, 0x4e, 0x2d, 0xd1, 0xcf, 0x49, 0x4d,
	0x49, 0x4f, 0x2d, 0xd2, 0x4f, 0x2c, 0xc8, 0xd4, 0x2f, 0x33, 0x84, 0xf2, 0xe2, 0xf3, 0xd3, 0xd2,
	0x8a, 0x53, 0x4b, 0xf4, 0x0a, 0x8a, 0xf2, 0x4b, 0xf2, 0x85, 0xe4, 0x92, 0xf3, 0x73, 0xf5, 0x90,
	0xf5, 0xe8, 0x41, 0x54, 0xe9, 0x25, 0x16, 0x64, 0xea, 0x95, 0x19, 0x2a, 0x1d, 0x61, 0xe4, 0xe2,
	0xf1, 0x01, 0x8b, 0xf8, 0x83, 0xb5, 0x09, 0xc9, 0x70, 0x71, 0x24, 0x26, 0x15, 0xe7, 0xe7, 0x94,
	0x96, 0xa4, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x7a, 0x30, 0x04, 0xc1, 0x45, 0x84, 0x22, 0xb9,
	0x38, 0x92, 0xf2, 0x4b, 0xf3, 0x52, 0x12, 0x8b, 0x2a, 0x25, 0x98, 0x14, 0x18, 0x35, 0xf8, 0x8c,
	0xac, 0xf5, 0xf0, 0xdb, 0xa0, 0x87, 0x6c, 0x3a, 0x94, 0xe3, 0x04, 0x35, 0x02, 0x64, 0x34, 0xcc,
	0x38, 0x25, 0x23, 0x2e, 0x3e, 0x54, 0x59, 0x21, 0x01, 0x2e, 0x1e, 0x1f, 0x57, 0x17, 0x77, 0xd7,
	0xa0, 0x78, 0x27, 0x57, 0x77, 0x4f, 0x3f, 0x01, 0x06, 0x21, 0x3e, 0x2e, 0x2e, 0xa8, 0x88, 0xab,
	0x9f, 0x8b, 0x00, 0xa3, 0x13, 0x3b, 0x17, 0x6b, 0x59, 0x62, 0x4e, 0x69, 0xaa, 0x93, 0x05, 0x17,
	0x01, 0x8f, 0x3a, 0x89, 0x21, 0xbb, 0xc3, 0xbf, 0xb4, 0x24, 0xb5, 0xc8, 0x19, 0xa4, 0x2e, 0x89,
	0x0d, 0x1c, 0x4e, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc0, 0x88, 0x69, 0x8e, 0x5d, 0x01,
	0x00, 0x00,
}
