// Code generated by protoc-gen-go. DO NOT EDIT.
// source: com/digitalasset/ledger/api/v1/transaction_filter.proto

package com_digitalasset_ledger_api_v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Used for filtering Transaction and Active Contract Set streams.
// Determines which on-ledger events will be served to the client.
type TransactionFilter struct {
	// Keys of the map determine which parties' on-ledger transactions are being queried.
	// Values of the map determine which events are disclosed in the stream per party.
	// At the minimum, a party needs to set an empty Filters message to receive any events.
	// Required
	FiltersByParty       map[string]*Filters `protobuf:"bytes,1,rep,name=filters_by_party,json=filtersByParty,proto3" json:"filters_by_party,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *TransactionFilter) Reset()         { *m = TransactionFilter{} }
func (m *TransactionFilter) String() string { return proto.CompactTextString(m) }
func (*TransactionFilter) ProtoMessage()    {}
func (*TransactionFilter) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac7e8af733d70c63, []int{0}
}

func (m *TransactionFilter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionFilter.Unmarshal(m, b)
}
func (m *TransactionFilter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionFilter.Marshal(b, m, deterministic)
}
func (m *TransactionFilter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionFilter.Merge(m, src)
}
func (m *TransactionFilter) XXX_Size() int {
	return xxx_messageInfo_TransactionFilter.Size(m)
}
func (m *TransactionFilter) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionFilter.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionFilter proto.InternalMessageInfo

func (m *TransactionFilter) GetFiltersByParty() map[string]*Filters {
	if m != nil {
		return m.FiltersByParty
	}
	return nil
}

type Filters struct {
	// If not set, no filters will be applied.
	// Optional
	Inclusive            *InclusiveFilters `protobuf:"bytes,1,opt,name=inclusive,proto3" json:"inclusive,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Filters) Reset()         { *m = Filters{} }
func (m *Filters) String() string { return proto.CompactTextString(m) }
func (*Filters) ProtoMessage()    {}
func (*Filters) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac7e8af733d70c63, []int{1}
}

func (m *Filters) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Filters.Unmarshal(m, b)
}
func (m *Filters) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Filters.Marshal(b, m, deterministic)
}
func (m *Filters) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Filters.Merge(m, src)
}
func (m *Filters) XXX_Size() int {
	return xxx_messageInfo_Filters.Size(m)
}
func (m *Filters) XXX_DiscardUnknown() {
	xxx_messageInfo_Filters.DiscardUnknown(m)
}

var xxx_messageInfo_Filters proto.InternalMessageInfo

func (m *Filters) GetInclusive() *InclusiveFilters {
	if m != nil {
		return m.Inclusive
	}
	return nil
}

// If no internal fields are set, no data will be returned.
type InclusiveFilters struct {
	// A collection of templates.
	// SHOULD NOT contain duplicates.
	// Required
	TemplateIds          []*Identifier `protobuf:"bytes,1,rep,name=template_ids,json=templateIds,proto3" json:"template_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *InclusiveFilters) Reset()         { *m = InclusiveFilters{} }
func (m *InclusiveFilters) String() string { return proto.CompactTextString(m) }
func (*InclusiveFilters) ProtoMessage()    {}
func (*InclusiveFilters) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac7e8af733d70c63, []int{2}
}

func (m *InclusiveFilters) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InclusiveFilters.Unmarshal(m, b)
}
func (m *InclusiveFilters) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InclusiveFilters.Marshal(b, m, deterministic)
}
func (m *InclusiveFilters) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InclusiveFilters.Merge(m, src)
}
func (m *InclusiveFilters) XXX_Size() int {
	return xxx_messageInfo_InclusiveFilters.Size(m)
}
func (m *InclusiveFilters) XXX_DiscardUnknown() {
	xxx_messageInfo_InclusiveFilters.DiscardUnknown(m)
}

var xxx_messageInfo_InclusiveFilters proto.InternalMessageInfo

func (m *InclusiveFilters) GetTemplateIds() []*Identifier {
	if m != nil {
		return m.TemplateIds
	}
	return nil
}

func init() {
	proto.RegisterType((*TransactionFilter)(nil), "com.digitalasset.ledger.api.v1.TransactionFilter")
	proto.RegisterMapType((map[string]*Filters)(nil), "com.digitalasset.ledger.api.v1.TransactionFilter.FiltersByPartyEntry")
	proto.RegisterType((*Filters)(nil), "com.digitalasset.ledger.api.v1.Filters")
	proto.RegisterType((*InclusiveFilters)(nil), "com.digitalasset.ledger.api.v1.InclusiveFilters")
}

func init() {
	proto.RegisterFile("com/digitalasset/ledger/api/v1/transaction_filter.proto", fileDescriptor_ac7e8af733d70c63)
}

var fileDescriptor_ac7e8af733d70c63 = []byte{
	// 309 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0xcf, 0x4b, 0xc3, 0x30,
	0x14, 0xc7, 0xe9, 0x86, 0xca, 0x52, 0x91, 0x19, 0x2f, 0x63, 0x82, 0x8c, 0x5d, 0x1c, 0x3b, 0xa4,
	0x6e, 0x1e, 0x14, 0x61, 0x97, 0xc9, 0x84, 0x1d, 0xfc, 0x41, 0xf1, 0xe2, 0xa9, 0x64, 0xed, 0xeb,
	0x88, 0xa6, 0x4d, 0x49, 0x5e, 0x0b, 0xfd, 0xaf, 0xfd, 0x13, 0xa4, 0xbf, 0x98, 0x3a, 0xb1, 0xa7,
	0x84, 0x97, 0xf7, 0xfd, 0x7c, 0x1e, 0x79, 0xe4, 0xc6, 0x57, 0x91, 0x13, 0x88, 0xad, 0x40, 0x2e,
	0xb9, 0x31, 0x80, 0x8e, 0x84, 0x60, 0x0b, 0xda, 0xe1, 0x89, 0x70, 0xb2, 0x99, 0x83, 0x9a, 0xc7,
	0x86, 0xfb, 0x28, 0x54, 0xec, 0x85, 0x42, 0x22, 0x68, 0x96, 0x68, 0x85, 0x8a, 0x5e, 0xf8, 0x2a,
	0x62, 0xdf, 0x83, 0xac, 0x0a, 0x32, 0x9e, 0x08, 0x96, 0xcd, 0x86, 0xd3, 0x16, 0x70, 0xc6, 0x65,
	0x0a, 0x15, 0x6b, 0xfc, 0x69, 0x91, 0xd3, 0xd7, 0x9d, 0xe8, 0xa1, 0xf4, 0x50, 0x45, 0xfa, 0x95,
	0xd1, 0x78, 0x9b, 0xdc, 0x4b, 0xb8, 0xc6, 0x7c, 0x60, 0x8d, 0xba, 0x13, 0x7b, 0xbe, 0x62, 0xff,
	0xcb, 0xd9, 0x1e, 0x8c, 0x55, 0x87, 0x59, 0xe6, 0x2f, 0x05, 0x67, 0x15, 0xa3, 0xce, 0xdd, 0x93,
	0xf0, 0x47, 0x71, 0xf8, 0x4e, 0xce, 0xfe, 0x68, 0xa3, 0x7d, 0xd2, 0xfd, 0x80, 0x42, 0x6d, 0x4d,
	0x7a, 0x6e, 0x71, 0xa5, 0x0b, 0x72, 0x50, 0x8e, 0x3f, 0xe8, 0x8c, 0xac, 0x89, 0x3d, 0xbf, 0x6c,
	0x1b, 0xa7, 0xa6, 0xba, 0x55, 0xea, 0xae, 0x73, 0x6b, 0x8d, 0xdf, 0xc8, 0x51, 0x5d, 0xa5, 0x4f,
	0xa4, 0x27, 0x62, 0x5f, 0xa6, 0x46, 0x64, 0x50, 0x5a, 0xec, 0xf9, 0x55, 0x1b, 0x71, 0xdd, 0x04,
	0x1a, 0xf4, 0x0e, 0x31, 0xe6, 0xa4, 0xff, 0xfb, 0x99, 0x3e, 0x92, 0x63, 0x84, 0x28, 0x91, 0x1c,
	0xc1, 0x13, 0x81, 0xa9, 0xff, 0x71, 0xda, 0xaa, 0x09, 0x20, 0x46, 0x11, 0x0a, 0xd0, 0xae, 0xdd,
	0xe4, 0xd7, 0x81, 0x59, 0x2e, 0x48, 0xcb, 0xfa, 0x97, 0xe7, 0x7b, 0x2b, 0x78, 0x4e, 0x11, 0xf4,
	0x7d, 0xd1, 0xbc, 0x39, 0x2c, 0xd7, 0x7e, 0xfd, 0x15, 0x00, 0x00, 0xff, 0xff, 0x9e, 0xe5, 0x46,
	0x05, 0x7d, 0x02, 0x00, 0x00,
}
