// Code generated by protoc-gen-go. DO NOT EDIT.
// source: com/digitalasset/ledger/api/v1/value.proto

package com_digitalasset_ledger_api_v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	protobuf "google/protobuf"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Encodes values that the ledger accepts as command arguments and emits as contract arguments.
type Value struct {
	// Types that are valid to be assigned to Sum:
	//	*Value_Record
	//	*Value_Variant
	//	*Value_ContractId
	//	*Value_List
	//	*Value_Int64
	//	*Value_Decimal
	//	*Value_Text
	//	*Value_Timestamp
	//	*Value_Party
	//	*Value_Bool
	//	*Value_Unit
	//	*Value_Date
	//	*Value_Optional
	//	*Value_Map
	Sum                  isValue_Sum `protobuf_oneof:"Sum"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Value) Reset()         { *m = Value{} }
func (m *Value) String() string { return proto.CompactTextString(m) }
func (*Value) ProtoMessage()    {}
func (*Value) Descriptor() ([]byte, []int) {
	return fileDescriptor_b20c1cae267d6e09, []int{0}
}

func (m *Value) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Value.Unmarshal(m, b)
}
func (m *Value) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Value.Marshal(b, m, deterministic)
}
func (m *Value) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Value.Merge(m, src)
}
func (m *Value) XXX_Size() int {
	return xxx_messageInfo_Value.Size(m)
}
func (m *Value) XXX_DiscardUnknown() {
	xxx_messageInfo_Value.DiscardUnknown(m)
}

var xxx_messageInfo_Value proto.InternalMessageInfo

type isValue_Sum interface {
	isValue_Sum()
}

type Value_Record struct {
	Record *Record `protobuf:"bytes,1,opt,name=record,proto3,oneof"`
}

type Value_Variant struct {
	Variant *Variant `protobuf:"bytes,2,opt,name=variant,proto3,oneof"`
}

type Value_ContractId struct {
	ContractId string `protobuf:"bytes,3,opt,name=contract_id,json=contractId,proto3,oneof"`
}

type Value_List struct {
	List *List `protobuf:"bytes,4,opt,name=list,proto3,oneof"`
}

type Value_Int64 struct {
	Int64 int64 `protobuf:"zigzag64,5,opt,name=int64,proto3,oneof"`
}

type Value_Decimal struct {
	Decimal string `protobuf:"bytes,6,opt,name=decimal,proto3,oneof"`
}

type Value_Text struct {
	Text string `protobuf:"bytes,8,opt,name=text,proto3,oneof"`
}

type Value_Timestamp struct {
	Timestamp int64 `protobuf:"fixed64,9,opt,name=timestamp,proto3,oneof"`
}

type Value_Party struct {
	Party string `protobuf:"bytes,11,opt,name=party,proto3,oneof"`
}

type Value_Bool struct {
	Bool bool `protobuf:"varint,12,opt,name=bool,proto3,oneof"`
}

type Value_Unit struct {
	Unit *protobuf.Empty `protobuf:"bytes,13,opt,name=unit,proto3,oneof"`
}

type Value_Date struct {
	Date int32 `protobuf:"varint,14,opt,name=date,proto3,oneof"`
}

type Value_Optional struct {
	Optional *Optional `protobuf:"bytes,15,opt,name=optional,proto3,oneof"`
}

type Value_Map struct {
	Map *Map `protobuf:"bytes,16,opt,name=map,proto3,oneof"`
}

func (*Value_Record) isValue_Sum() {}

func (*Value_Variant) isValue_Sum() {}

func (*Value_ContractId) isValue_Sum() {}

func (*Value_List) isValue_Sum() {}

func (*Value_Int64) isValue_Sum() {}

func (*Value_Decimal) isValue_Sum() {}

func (*Value_Text) isValue_Sum() {}

func (*Value_Timestamp) isValue_Sum() {}

func (*Value_Party) isValue_Sum() {}

func (*Value_Bool) isValue_Sum() {}

func (*Value_Unit) isValue_Sum() {}

func (*Value_Date) isValue_Sum() {}

func (*Value_Optional) isValue_Sum() {}

func (*Value_Map) isValue_Sum() {}

func (m *Value) GetSum() isValue_Sum {
	if m != nil {
		return m.Sum
	}
	return nil
}

func (m *Value) GetRecord() *Record {
	if x, ok := m.GetSum().(*Value_Record); ok {
		return x.Record
	}
	return nil
}

func (m *Value) GetVariant() *Variant {
	if x, ok := m.GetSum().(*Value_Variant); ok {
		return x.Variant
	}
	return nil
}

func (m *Value) GetContractId() string {
	if x, ok := m.GetSum().(*Value_ContractId); ok {
		return x.ContractId
	}
	return ""
}

func (m *Value) GetList() *List {
	if x, ok := m.GetSum().(*Value_List); ok {
		return x.List
	}
	return nil
}

func (m *Value) GetInt64() int64 {
	if x, ok := m.GetSum().(*Value_Int64); ok {
		return x.Int64
	}
	return 0
}

func (m *Value) GetDecimal() string {
	if x, ok := m.GetSum().(*Value_Decimal); ok {
		return x.Decimal
	}
	return ""
}

func (m *Value) GetText() string {
	if x, ok := m.GetSum().(*Value_Text); ok {
		return x.Text
	}
	return ""
}

func (m *Value) GetTimestamp() int64 {
	if x, ok := m.GetSum().(*Value_Timestamp); ok {
		return x.Timestamp
	}
	return 0
}

func (m *Value) GetParty() string {
	if x, ok := m.GetSum().(*Value_Party); ok {
		return x.Party
	}
	return ""
}

func (m *Value) GetBool() bool {
	if x, ok := m.GetSum().(*Value_Bool); ok {
		return x.Bool
	}
	return false
}

func (m *Value) GetUnit() *protobuf.Empty {
	if x, ok := m.GetSum().(*Value_Unit); ok {
		return x.Unit
	}
	return nil
}

func (m *Value) GetDate() int32 {
	if x, ok := m.GetSum().(*Value_Date); ok {
		return x.Date
	}
	return 0
}

func (m *Value) GetOptional() *Optional {
	if x, ok := m.GetSum().(*Value_Optional); ok {
		return x.Optional
	}
	return nil
}

func (m *Value) GetMap() *Map {
	if x, ok := m.GetSum().(*Value_Map); ok {
		return x.Map
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Value) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Value_Record)(nil),
		(*Value_Variant)(nil),
		(*Value_ContractId)(nil),
		(*Value_List)(nil),
		(*Value_Int64)(nil),
		(*Value_Decimal)(nil),
		(*Value_Text)(nil),
		(*Value_Timestamp)(nil),
		(*Value_Party)(nil),
		(*Value_Bool)(nil),
		(*Value_Unit)(nil),
		(*Value_Date)(nil),
		(*Value_Optional)(nil),
		(*Value_Map)(nil),
	}
}

// Contains nested values.
type Record struct {
	// Omitted from the transaction stream when verbose streaming is not enabled.
	// Optional when submitting commands.
	RecordId *Identifier `protobuf:"bytes,1,opt,name=record_id,json=recordId,proto3" json:"record_id,omitempty"`
	// The nested values of the record.
	// Required
	Fields               []*RecordField `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Record) Reset()         { *m = Record{} }
func (m *Record) String() string { return proto.CompactTextString(m) }
func (*Record) ProtoMessage()    {}
func (*Record) Descriptor() ([]byte, []int) {
	return fileDescriptor_b20c1cae267d6e09, []int{1}
}

func (m *Record) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Record.Unmarshal(m, b)
}
func (m *Record) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Record.Marshal(b, m, deterministic)
}
func (m *Record) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Record.Merge(m, src)
}
func (m *Record) XXX_Size() int {
	return xxx_messageInfo_Record.Size(m)
}
func (m *Record) XXX_DiscardUnknown() {
	xxx_messageInfo_Record.DiscardUnknown(m)
}

var xxx_messageInfo_Record proto.InternalMessageInfo

func (m *Record) GetRecordId() *Identifier {
	if m != nil {
		return m.RecordId
	}
	return nil
}

func (m *Record) GetFields() []*RecordField {
	if m != nil {
		return m.Fields
	}
	return nil
}

// A named nested value within a record.
type RecordField struct {
	// Omitted from the transaction stream when verbose streaming is not enabled.
	// If any of the keys are omitted within a single record, the order of fields MUST match the order of declaration in the DAML template.
	// Optional, when submitting commands.
	Label string `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	// A nested value of a record.
	// Required
	Value                *Value   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RecordField) Reset()         { *m = RecordField{} }
func (m *RecordField) String() string { return proto.CompactTextString(m) }
func (*RecordField) ProtoMessage()    {}
func (*RecordField) Descriptor() ([]byte, []int) {
	return fileDescriptor_b20c1cae267d6e09, []int{2}
}

func (m *RecordField) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecordField.Unmarshal(m, b)
}
func (m *RecordField) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecordField.Marshal(b, m, deterministic)
}
func (m *RecordField) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecordField.Merge(m, src)
}
func (m *RecordField) XXX_Size() int {
	return xxx_messageInfo_RecordField.Size(m)
}
func (m *RecordField) XXX_DiscardUnknown() {
	xxx_messageInfo_RecordField.DiscardUnknown(m)
}

var xxx_messageInfo_RecordField proto.InternalMessageInfo

func (m *RecordField) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *RecordField) GetValue() *Value {
	if m != nil {
		return m.Value
	}
	return nil
}

// Unique identifier of an entity.
type Identifier struct {
	// The identifier of the DAML package that contains the entity.
	// Required
	PackageId string `protobuf:"bytes,1,opt,name=package_id,json=packageId,proto3" json:"package_id,omitempty"`
	// The identifier of the entity (unique within the package)
	// DEPRECATED: use ``module_name`` and ``entity_name`` instead
	// Optional
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"` // Deprecated: Do not use.
	// The dot-separated module name of the identifier.
	// Required
	ModuleName string `protobuf:"bytes,3,opt,name=module_name,json=moduleName,proto3" json:"module_name,omitempty"`
	// The dot-separated name of the entity (e.g. record, template, ...) within the module.
	// Required
	EntityName           string   `protobuf:"bytes,4,opt,name=entity_name,json=entityName,proto3" json:"entity_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Identifier) Reset()         { *m = Identifier{} }
func (m *Identifier) String() string { return proto.CompactTextString(m) }
func (*Identifier) ProtoMessage()    {}
func (*Identifier) Descriptor() ([]byte, []int) {
	return fileDescriptor_b20c1cae267d6e09, []int{3}
}

func (m *Identifier) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Identifier.Unmarshal(m, b)
}
func (m *Identifier) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Identifier.Marshal(b, m, deterministic)
}
func (m *Identifier) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Identifier.Merge(m, src)
}
func (m *Identifier) XXX_Size() int {
	return xxx_messageInfo_Identifier.Size(m)
}
func (m *Identifier) XXX_DiscardUnknown() {
	xxx_messageInfo_Identifier.DiscardUnknown(m)
}

var xxx_messageInfo_Identifier proto.InternalMessageInfo

func (m *Identifier) GetPackageId() string {
	if m != nil {
		return m.PackageId
	}
	return ""
}

// Deprecated: Do not use.
func (m *Identifier) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Identifier) GetModuleName() string {
	if m != nil {
		return m.ModuleName
	}
	return ""
}

func (m *Identifier) GetEntityName() string {
	if m != nil {
		return m.EntityName
	}
	return ""
}

// A value with alternative representations.
type Variant struct {
	// Omitted from the transaction stream when verbose streaming is not enabled.
	// Optional when submitting commands.
	VariantId *Identifier `protobuf:"bytes,1,opt,name=variant_id,json=variantId,proto3" json:"variant_id,omitempty"`
	// Determines which of the Variant's alternatives is encoded in this message.
	// Required
	Constructor string `protobuf:"bytes,2,opt,name=constructor,proto3" json:"constructor,omitempty"`
	// The value encoded within the Variant.
	// Required
	Value                *Value   `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Variant) Reset()         { *m = Variant{} }
func (m *Variant) String() string { return proto.CompactTextString(m) }
func (*Variant) ProtoMessage()    {}
func (*Variant) Descriptor() ([]byte, []int) {
	return fileDescriptor_b20c1cae267d6e09, []int{4}
}

func (m *Variant) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Variant.Unmarshal(m, b)
}
func (m *Variant) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Variant.Marshal(b, m, deterministic)
}
func (m *Variant) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Variant.Merge(m, src)
}
func (m *Variant) XXX_Size() int {
	return xxx_messageInfo_Variant.Size(m)
}
func (m *Variant) XXX_DiscardUnknown() {
	xxx_messageInfo_Variant.DiscardUnknown(m)
}

var xxx_messageInfo_Variant proto.InternalMessageInfo

func (m *Variant) GetVariantId() *Identifier {
	if m != nil {
		return m.VariantId
	}
	return nil
}

func (m *Variant) GetConstructor() string {
	if m != nil {
		return m.Constructor
	}
	return ""
}

func (m *Variant) GetValue() *Value {
	if m != nil {
		return m.Value
	}
	return nil
}

// A homogenous collection of values.
type List struct {
	// The elements must all be of the same concrete value type.
	// Optional
	Elements             []*Value `protobuf:"bytes,1,rep,name=elements,proto3" json:"elements,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *List) Reset()         { *m = List{} }
func (m *List) String() string { return proto.CompactTextString(m) }
func (*List) ProtoMessage()    {}
func (*List) Descriptor() ([]byte, []int) {
	return fileDescriptor_b20c1cae267d6e09, []int{5}
}

func (m *List) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_List.Unmarshal(m, b)
}
func (m *List) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_List.Marshal(b, m, deterministic)
}
func (m *List) XXX_Merge(src proto.Message) {
	xxx_messageInfo_List.Merge(m, src)
}
func (m *List) XXX_Size() int {
	return xxx_messageInfo_List.Size(m)
}
func (m *List) XXX_DiscardUnknown() {
	xxx_messageInfo_List.DiscardUnknown(m)
}

var xxx_messageInfo_List proto.InternalMessageInfo

func (m *List) GetElements() []*Value {
	if m != nil {
		return m.Elements
	}
	return nil
}

// Corresponds to Java's Optional type, Scala's Option, and Haskell's Maybe.
// The reason why we need to wrap this in an additional ``message`` is that we
// need to be able to encode the ``None`` case in the ``Value`` oneof.
type Optional struct {
	Value                *Value   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Optional) Reset()         { *m = Optional{} }
func (m *Optional) String() string { return proto.CompactTextString(m) }
func (*Optional) ProtoMessage()    {}
func (*Optional) Descriptor() ([]byte, []int) {
	return fileDescriptor_b20c1cae267d6e09, []int{6}
}

func (m *Optional) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Optional.Unmarshal(m, b)
}
func (m *Optional) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Optional.Marshal(b, m, deterministic)
}
func (m *Optional) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Optional.Merge(m, src)
}
func (m *Optional) XXX_Size() int {
	return xxx_messageInfo_Optional.Size(m)
}
func (m *Optional) XXX_DiscardUnknown() {
	xxx_messageInfo_Optional.DiscardUnknown(m)
}

var xxx_messageInfo_Optional proto.InternalMessageInfo

func (m *Optional) GetValue() *Value {
	if m != nil {
		return m.Value
	}
	return nil
}

type Map struct {
	Entries              []*Map_Entry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Map) Reset()         { *m = Map{} }
func (m *Map) String() string { return proto.CompactTextString(m) }
func (*Map) ProtoMessage()    {}
func (*Map) Descriptor() ([]byte, []int) {
	return fileDescriptor_b20c1cae267d6e09, []int{7}
}

func (m *Map) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Map.Unmarshal(m, b)
}
func (m *Map) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Map.Marshal(b, m, deterministic)
}
func (m *Map) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Map.Merge(m, src)
}
func (m *Map) XXX_Size() int {
	return xxx_messageInfo_Map.Size(m)
}
func (m *Map) XXX_DiscardUnknown() {
	xxx_messageInfo_Map.DiscardUnknown(m)
}

var xxx_messageInfo_Map proto.InternalMessageInfo

func (m *Map) GetEntries() []*Map_Entry {
	if m != nil {
		return m.Entries
	}
	return nil
}

type Map_Entry struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                *Value   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Map_Entry) Reset()         { *m = Map_Entry{} }
func (m *Map_Entry) String() string { return proto.CompactTextString(m) }
func (*Map_Entry) ProtoMessage()    {}
func (*Map_Entry) Descriptor() ([]byte, []int) {
	return fileDescriptor_b20c1cae267d6e09, []int{7, 0}
}

func (m *Map_Entry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Map_Entry.Unmarshal(m, b)
}
func (m *Map_Entry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Map_Entry.Marshal(b, m, deterministic)
}
func (m *Map_Entry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Map_Entry.Merge(m, src)
}
func (m *Map_Entry) XXX_Size() int {
	return xxx_messageInfo_Map_Entry.Size(m)
}
func (m *Map_Entry) XXX_DiscardUnknown() {
	xxx_messageInfo_Map_Entry.DiscardUnknown(m)
}

var xxx_messageInfo_Map_Entry proto.InternalMessageInfo

func (m *Map_Entry) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Map_Entry) GetValue() *Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func init() {
	proto.RegisterType((*Value)(nil), "com.digitalasset.ledger.api.v1.Value")
	proto.RegisterType((*Record)(nil), "com.digitalasset.ledger.api.v1.Record")
	proto.RegisterType((*RecordField)(nil), "com.digitalasset.ledger.api.v1.RecordField")
	proto.RegisterType((*Identifier)(nil), "com.digitalasset.ledger.api.v1.Identifier")
	proto.RegisterType((*Variant)(nil), "com.digitalasset.ledger.api.v1.Variant")
	proto.RegisterType((*List)(nil), "com.digitalasset.ledger.api.v1.List")
	proto.RegisterType((*Optional)(nil), "com.digitalasset.ledger.api.v1.Optional")
	proto.RegisterType((*Map)(nil), "com.digitalasset.ledger.api.v1.Map")
	proto.RegisterType((*Map_Entry)(nil), "com.digitalasset.ledger.api.v1.Map.Entry")
}

func init() {
	proto.RegisterFile("com/digitalasset/ledger/api/v1/value.proto", fileDescriptor_b20c1cae267d6e09)
}

var fileDescriptor_b20c1cae267d6e09 = []byte{
	// 712 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0xdb, 0x6e, 0xdb, 0x38,
	0x10, 0x35, 0x6d, 0xc9, 0xb1, 0xc6, 0xbb, 0x9b, 0x80, 0x08, 0x02, 0xc2, 0x8b, 0x4d, 0xb4, 0xde,
	0x9b, 0x36, 0x2d, 0xe4, 0x26, 0x2d, 0x5a, 0xa0, 0x7d, 0x69, 0x1d, 0x24, 0xb1, 0x81, 0xa6, 0x01,
	0x58, 0x20, 0xaf, 0x29, 0x2d, 0x31, 0x06, 0x11, 0xdd, 0x20, 0x51, 0x46, 0xfd, 0x01, 0xfd, 0x85,
	0x7e, 0x40, 0x7f, 0xa1, 0x5f, 0xd3, 0xbf, 0x29, 0x78, 0x51, 0x1c, 0xe4, 0xa1, 0x0e, 0xd2, 0x37,
	0xcf, 0xe1, 0x39, 0x67, 0x46, 0x9c, 0x19, 0x1a, 0xf6, 0xa3, 0x3c, 0x1d, 0xc5, 0x62, 0x2e, 0x24,
	0x4b, 0x58, 0x55, 0x71, 0x39, 0x4a, 0x78, 0x3c, 0xe7, 0xe5, 0x88, 0x15, 0x62, 0xb4, 0x38, 0x18,
	0x2d, 0x58, 0x52, 0xf3, 0xb0, 0x28, 0x73, 0x99, 0xe3, 0xdd, 0x28, 0x4f, 0xc3, 0xdb, 0xdc, 0xd0,
	0x70, 0x43, 0x56, 0x88, 0x70, 0x71, 0x30, 0xf8, 0x7d, 0x9e, 0xe7, 0xf3, 0x84, 0x8f, 0x34, 0x7b,
	0x56, 0x5f, 0x8d, 0x78, 0x5a, 0xc8, 0xa5, 0x11, 0x0f, 0xf6, 0xee, 0x1e, 0x4a, 0x91, 0xf2, 0x4a,
	0xb2, 0xb4, 0xb0, 0x84, 0xdd, 0xbb, 0x84, 0xb8, 0x2e, 0x99, 0x14, 0x79, 0x66, 0xce, 0x87, 0xdf,
	0x1c, 0x70, 0x2f, 0x54, 0x35, 0xf8, 0x35, 0x74, 0x4b, 0x1e, 0xe5, 0x65, 0x4c, 0x90, 0x8f, 0x82,
	0xfe, 0xe1, 0xbf, 0xe1, 0x8f, 0x0b, 0x0b, 0xa9, 0x66, 0x4f, 0x5a, 0xd4, 0xea, 0xf0, 0x11, 0x6c,
	0x2c, 0x58, 0x29, 0x58, 0x26, 0x49, 0x5b, 0x5b, 0xfc, 0xb7, 0xce, 0xe2, 0xc2, 0xd0, 0x27, 0x2d,
	0xda, 0x28, 0xf1, 0x9f, 0xd0, 0x8f, 0xf2, 0x4c, 0x96, 0x2c, 0x92, 0x97, 0x22, 0x26, 0x1d, 0x1f,
	0x05, 0xde, 0xa4, 0x45, 0xa1, 0x01, 0xa7, 0x31, 0x7e, 0x09, 0x4e, 0x22, 0x2a, 0x49, 0x1c, 0x9d,
	0xe4, 0xef, 0x75, 0x49, 0xde, 0x8a, 0x4a, 0x65, 0xd0, 0x1a, 0x3c, 0x00, 0x57, 0x64, 0xf2, 0xf9,
	0x33, 0xe2, 0xfa, 0x28, 0xc0, 0xe3, 0xf6, 0x13, 0x34, 0x69, 0x51, 0x03, 0xe1, 0x01, 0x6c, 0xc4,
	0x3c, 0x12, 0x29, 0x4b, 0x48, 0xd7, 0xa6, 0x6d, 0x00, 0xbc, 0x0d, 0x8e, 0xe4, 0x1f, 0x25, 0xe9,
	0xd9, 0x03, 0x1d, 0xe1, 0x21, 0x78, 0x37, 0x17, 0x4e, 0x3c, 0x1f, 0x05, 0x5b, 0xd6, 0x71, 0x05,
	0xe3, 0x1d, 0x70, 0x0b, 0x56, 0xca, 0x25, 0xe9, 0x5b, 0xa9, 0x09, 0x95, 0xe3, 0x2c, 0xcf, 0x13,
	0xf2, 0x8b, 0x8f, 0x82, 0x9e, 0x72, 0x54, 0x11, 0x7e, 0x0c, 0x4e, 0x9d, 0x09, 0x49, 0x7e, 0xd5,
	0xdf, 0xb6, 0x13, 0x9a, 0xf6, 0x85, 0x4d, 0xfb, 0xc2, 0x63, 0xd5, 0x7c, 0xc5, 0x56, 0x2c, 0xe5,
	0x11, 0x33, 0xc9, 0xc9, 0x6f, 0x3e, 0x0a, 0x5c, 0x85, 0xaa, 0x08, 0x9f, 0x40, 0x2f, 0x2f, 0x54,
	0x8f, 0x59, 0x42, 0x36, 0xb5, 0x4f, 0xb0, 0xee, 0x8e, 0xce, 0x2d, 0x7f, 0xd2, 0xa2, 0x37, 0x5a,
	0xfc, 0x02, 0x3a, 0x29, 0x2b, 0xc8, 0x96, 0xb6, 0xf8, 0x6b, 0x9d, 0xc5, 0x19, 0x2b, 0x26, 0x2d,
	0xaa, 0x14, 0x63, 0x17, 0x3a, 0xef, 0xeb, 0x74, 0xf8, 0x19, 0x41, 0xd7, 0x0c, 0x09, 0x3e, 0x05,
	0xcf, 0x0c, 0x89, 0xea, 0xa9, 0x99, 0xaf, 0xfd, 0x75, 0x86, 0xd3, 0x98, 0x67, 0x52, 0x5c, 0x09,
	0x5e, 0xd2, 0x9e, 0x11, 0x4f, 0xd5, 0x8c, 0x75, 0xaf, 0x04, 0x4f, 0xe2, 0x8a, 0xb4, 0xfd, 0x4e,
	0xd0, 0x3f, 0x7c, 0x74, 0xbf, 0x29, 0x3d, 0x51, 0x1a, 0x6a, 0xa5, 0xc3, 0x0f, 0xd0, 0xbf, 0x05,
	0xe3, 0x6d, 0x70, 0x13, 0x36, 0xe3, 0x89, 0x2e, 0xcc, 0xa3, 0x26, 0xc0, 0xaf, 0xc0, 0xd5, 0x6b,
	0x6a, 0x67, 0xf9, 0x9f, 0xf5, 0xb3, 0x9c, 0xd4, 0x9c, 0x1a, 0xcd, 0xf0, 0x13, 0x02, 0x58, 0xd5,
	0x8f, 0xff, 0x00, 0x28, 0x58, 0x74, 0xcd, 0xe6, 0xbc, 0xf9, 0x7e, 0x8f, 0x7a, 0x16, 0x99, 0xc6,
	0x78, 0x07, 0x9c, 0x8c, 0xa5, 0x26, 0x93, 0x37, 0x6e, 0x13, 0x44, 0x75, 0x8c, 0xf7, 0xa0, 0x9f,
	0xe6, 0x71, 0x9d, 0xf0, 0x4b, 0x7d, 0xac, 0x77, 0x81, 0x82, 0x81, 0xde, 0x59, 0x82, 0xca, 0x21,
	0x97, 0x86, 0xe0, 0x18, 0x82, 0x81, 0x14, 0x61, 0xf8, 0x15, 0xc1, 0x86, 0x5d, 0x32, 0x3c, 0x05,
	0xb0, 0x4b, 0xf6, 0xb0, 0x26, 0x78, 0x56, 0x3d, 0x8d, 0xb1, 0xaf, 0x97, 0xb4, 0x92, 0x65, 0x1d,
	0xc9, 0xbc, 0x34, 0x75, 0xd3, 0xdb, 0xd0, 0xea, 0xf6, 0x3a, 0x0f, 0xb8, 0xbd, 0x29, 0x38, 0x6a,
	0x69, 0xf1, 0x1b, 0xe8, 0xf1, 0x84, 0xa7, 0x3c, 0x93, 0x15, 0x41, 0xba, 0xdd, 0xf7, 0xf4, 0xb9,
	0x91, 0x0d, 0x4f, 0xa1, 0xd7, 0xcc, 0xf6, 0xaa, 0x26, 0xf4, 0x80, 0x9a, 0xbe, 0x20, 0xe8, 0x9c,
	0xb1, 0x42, 0x3d, 0x72, 0x3c, 0x93, 0xa5, 0xe0, 0x4d, 0x49, 0xff, 0xdf, 0x63, 0x31, 0xc2, 0xe3,
	0x4c, 0x96, 0x4b, 0xda, 0x28, 0x07, 0x17, 0xe0, 0x6a, 0x04, 0x6f, 0x41, 0xe7, 0x9a, 0x2f, 0xed,
	0x44, 0xa8, 0x9f, 0x3f, 0x35, 0x76, 0xe3, 0x03, 0x58, 0xf3, 0x6f, 0x32, 0xde, 0xd4, 0xfc, 0xf3,
	0x5a, 0xf2, 0xf2, 0x48, 0x11, 0x66, 0x5d, 0xfd, 0xb4, 0x3c, 0xfd, 0x1e, 0x00, 0x00, 0xff, 0xff,
	0x4c, 0x3d, 0x0d, 0x6d, 0xb3, 0x06, 0x00, 0x00,
}
